name: Deploy
run-name: Deploy
on: 
  workflow_dispatch:
  workflow_call:
    # secrets:
    #   render-token:
    #     type: string
    #     required: true
    #   render-service-id:
    #     type: string
    #     required: true
    #   test:
    #     type: string
    #     required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "secrets.test:" ${{ secrets.test }}
          if [ ${{ secrets.render-token }} ]; then
            echo Render token present 
          else
            echo Missing render token
          fi
          if [ ${{ secrets.GITHUB_TOKEN }} ]; then
            echo Github token present 
          else
            echo Missing github token
          fi
          if [ ${{ secrets.render-service-id }} ]; then
            echo Render service id present 
          else
            echo Missing render service id
          fi

  deploy:
    runs-on: ubuntu-latest
    env:
      RENDER_TOKEN: ${{ secrets.render-token }}
      RENDER_SERVICE_ID: ${{ secrets.render-service-id }}
    steps:
      - name: Deploy to Render
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          retries: 20
          wait: 16000
          sleep: 30000
