name: Release
run-name: Release
on: 
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  # test:
  #   uses: ./.github/workflows/test.yml

  release:
    # needs: [test]
    env:
      RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      TEST: ${{ secrets.TEST }}
    uses: ./.github/workflows/deploy.yml
    secrets:
      render-token: ${{ secrets.RENDER_TOKEN }}
      render-service-id: ${{ secrets.RENDER_SERVICE_ID }}
      test: ${{ secrets.TEST }}

  # smoke_test:

  # rollback
  # if fail()
