name: Release
run-name: Release
on: 
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  # test:
  #   uses: ./.github/workflows/test.yml

  check:
    # needs: [test]
    uses: ./.github/workflows/check_deployment.yml
    secrets: inherit

  # smoke_test
  # if fail() rollback
