name: Release
run-name: Release
on: 
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  # test:
  #   uses: ./.github/workflows/test.yml

  deploy:
    # needs: [test]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  # smoke_test:

  # rollback
  # if fail()
