name: Release
run-name: Release
on: 
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
          echo Merged? ${{ github.event.pull_request.merged }}
          echo Workflow dispatch? ${{ github.event.workflow_dispatch }}
          echo Event? ${{ github.event }}
