name: Release
run-name: Release
on: 
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yml

  check_deployment:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    secrets: inherit
    uses: ./.github/workflows/check_deployment.yml

  # test on production
  # rollback on failure
