name: Release
run-name: Release
on: 
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yml

  # wait for deployment
  # test on production
  # rollback on failure
