name: Release
run-name: Release
on: 
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yml

  check_deployment:
    secrets: inherit
    uses: ./.github/workflows/check_deployment.yml

  # test on production
  # rollback on failure
