name: Test
run-name: Test
on: 
  workflow_call:
  pull_request:
    types: [opened, synchronize]
jobs:
  cypress-run:
    if: startsWith(github.head_ref, 'main/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "Github head ref: ${{ github.head_ref }}"

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with: 
          build: yarn run build
          start: yarn start
